web:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - ./application:/application
        - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
        - php

#php:
#    image: php:7-fpm
#    command: "bash -c 'cd /application && php composer.phar install && php-fpm'"
#    volumes:
#        - ./application:/application
#        - ./php_pdo.ini:/usr/local/etc/php/conf.d/pdo.ini
#    links:
#        - db

php:
  build: ./application
  command: "bash -c 'php composer.phar install && php-fpm'"
  working_dir: /application
  volumes:
    - ./application:/application
    - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
  links:
    - db

db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
        - ./database/data:/var/lib/mysql
        - ./database/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: webforum

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
        - db
    ports:
        - "80:80"